apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-hello
  namespace: dev
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
      app: app-hello
      tier: backend
  replicas: 1
  template:
    metadata:
      namespace: dev
      labels:
        app: app-hello
        tier: backend
    spec:        
      containers:
      - name: app-hello
        image: echobuild:dev0.1
        ports:
          - containerPort: 8080
            name: "http-server"            
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
        #  limits:
        #    memory: "524Mi"
        #    cpu: "500m"         
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 1            

          